#!/bin/sh

# This script assumes that lpd passes the username and hostname of
# the user that owns the print job in arguments 5 and 7, respectively.

# Substitute your favorite ascii-to-postscript filter here...
# note: with gnu enscript, the '--pass-through' flag makes the filter
# transparent to postscript files.  Handy.

/usr/local/bin/enscript -M Letterdj --pass-through --lineprinter -o - |\
/usr/local/gnu/bin/gs -q -dNOPAUSE -sDEVICE=pbmraw -r360x360 \
	-sOutputFile=- - \
|/usr/local/sbin/lpstyl -a 'PaperShredder:ColorStyleWriter2400AT' -u ${5}@${7}

